### ISSUE TITLE
Can't download dataset, server is down

### ISSUE THREAD

**Issue by languagemaniac** [walker-hyf/MnTTS#4]
I'm trying to download the dataset from the site linked in the readme file
 (https://mglip.com/corpus/corpus_detail.html?corpusid=20220819185345) 

But it looks like the server is down, could it be uploaded elsewhere?

**Comment by walker-hyf** [comment]
http://mglip.com/corpus/corpus_detail.html?corpusid=20220819185345

**Comment by languagemaniac** [comment]
> http://mglip.com/corpus/corpus_detail.html?corpusid=20220819185345

I'm getting a "Server refused to connect" error on both links

Edit: they're actually the same link
